-- same as tokyonight_moon, but with tokyonight_night's background
-- ~/.local/share/nvim/lazy/tokyonight.nvim/extras/wezterm/tokyonight_moon.toml
return {
	tokyonight_soft_moon = {
		ansi = {
			"#1b1d2b",
			"#ff757f",
			"#c3e88d",
			"#ffc777",
			"#82aaff",
			"#c099ff",
			"#86e1fc",
			"#828bb8",
		},
		background = "#1a1b26",
		brights = {
			"#2f334d",
			"#ff8d94",
			"#c7fb6d",
			"#ffd8ab",
			"#9ab8ff",
			"#caabff",
			"#b2ebff",
			"#c8d3f5",
		},
		compose_cursor = "#ff966c",
		cursor_bg = "#c8d3f5",
		cursor_border = "#c8d3f5",
		cursor_fg = "#222436",
		foreground = "#c8d3f5",
		scrollbar_thumb = "#2f334d",
		selection_bg = "#2d3f76",
		selection_fg = "#c8d3f5",
		split = "#82aaff",
		tab_bar = {
			active_tab = {
				bg_color = "#82aaff",
				fg_color = "#1a1b26",
				intensity = "Normal",
				italic = false,
				strikethrough = false,
				underline = "None",
			},
			background = "#222436",
			inactive_tab = {
				fg_color = "#82aaff",
				bg_color = "#2f334d",
				intensity = "Normal",
				italic = false,
				strikethrough = false,
				underline = "None",
			},
			inactive_tab_edge = "#d0d5e3",
			inactive_tab_hover = {
				fg_color = "#82aaff",
				bg_color = "#2f334d",
				intensity = "Normal",
				italic = false,
				strikethrough = false,
				underline = "None",
			},
			new_tab = {
				fg_color = "#82aaff",
				bg_color = "#222436",
				intensity = "Normal",
				italic = false,
				strikethrough = false,
				underline = "None",
			},
			new_tab_hover = {
				fg_color = "#82aaff",
				bg_color = "#222436",
				intensity = "Bold",
				italic = false,
				strikethrough = false,
				underline = "None",
			},
		},
	},
	tokyonight_day = {
		foreground = "#3760bf",
		background = "#e1e2e7",
		cursor_bg = "#3760bf",
		cursor_border = "#3760bf",
		cursor_fg = "#e1e2e7",
		selection_bg = "#b7c1e3",
		selection_fg = "#3760bf",
		split = "#2e7de9",
		compose_cursor = "#b15c00",
		scrollbar_thumb = "#c4c8da",
		ansi = {
			"#b4b5b9",
			"#f52a65",
			"#587539",
			"#8c6c3e",
			"#2e7de9",
			"#9854f1",
			"#007197",
			"#6172b0",
		},
		brights = {
			"#c4c8da",
			"#ff4774",
			"#5c8524",
			"#a27629",
			"#358aff",
			"#a463ff",
			"#007ea8",
			"#3760bf",
		},
		tab_bar = {
			inactive_tab_edge = "#d0d5e3",
			background = "#e1e2e7",
			active_tab = {
				fg_color = "#d0d5e3",
				bg_color = "#2e7de9",
			},
			inactive_tab = {
				fg_color = "#8990b3",
				bg_color = "#c4c8da",
			},
			inactive_tab_hover = {
				fg_color = "#2e7de9",
				bg_color = "#c4c8da",
				intensity = "Bold",
			},
			new_tab_hover = {
				fg_color = "#2e7de9",
				bg_color = "#e1e2e7",
				intensity = "Bold",
			},
			new_tab = {
				fg_color = "#2e7de9",
				bg_color = "#e1e2e7",
			},
		},
	},
}
