-- same as tokyonight_moon, but with tokyonight_night's background
return {
	tokyonight_dark_moon = {
		ansi = {
			"#b4b5b9",
			"#f52a65",
			"#587539",
			"#8c6c3e",
			"#2e7de9",
			"#9854f1",
			"#007197",
			"#6172b0",
		},
		background = "#1a1b26",
		brights = {
			"#a1a6c5",
			"#f52a65",
			"#587539",
			"#8c6c3e",
			"#2e7de9",
			"#9854f1",
			"#007197",
			"#3760bf",
		},
		compose_cursor = "#b15c00",
		cursor_bg = "#3760bf",
		cursor_border = "#3760bf",
		cursor_fg = "#e1e2e7",
		foreground = "#3760bf",
		indexed = {},
		scrollbar_thumb = "#c4c8da",
		selection_bg = "#b7c1e3",
		selection_fg = "#3760bf",
		split = "#2e7de9",
		tab_bar = {
			active_tab = {
				bg_color = "#2e7de9",
				fg_color = "#d0d5e3",
				intensity = "Normal",
				italic = false,
				strikethrough = false,
				underline = "None",
			},
			background = "#e1e2e7",
			inactive_tab = {
				bg_color = "#c4c8da",
				fg_color = "#8990b3",
				intensity = "Normal",
				italic = false,
				strikethrough = false,
				underline = "None",
			},
			inactive_tab_edge = "#d0d5e3",
			inactive_tab_hover = {
				bg_color = "#c4c8da",
				fg_color = "#2e7de9",
				intensity = "Normal",
				italic = false,
				strikethrough = false,
				underline = "None",
			},
			new_tab = {
				bg_color = "#e1e2e7",
				fg_color = "#2e7de9",
				intensity = "Normal",
				italic = false,
				strikethrough = false,
				underline = "None",
			},
			new_tab_hover = {
				bg_color = "#e1e2e7",
				fg_color = "#2e7de9",
				intensity = "Bold",
				italic = false,
				strikethrough = false,
				underline = "None",
			},
		},
	},
}
