#!/bin/bash

# exit if no graphical interface
if [ -z "$DISPLAY" ]; then
  exit 0
fi

current_theme_mode="light"

dconf watch /org/gnome/desktop/interface/color-scheme | while read -r gnome_theme_mode; do
  if [[ "$gnome_theme_mode" == "'prefer-dark'" ]]; then
    if [[ "$current_theme_mode" == "light" ]]; then
      current_theme_mode="dark"
      tmux source-file ~/dotfiles/tmux/colors/tokyonight_moon
    fi
  elif [[ "$gnome_theme_mode" == "'default'" ]]; then
    if [[ "$current_theme_mode" == "dark" ]]; then
      current_theme_mode="light"
      tmux source-file ~/dotfiles/tmux/colors/tokyonight_day
    fi
  fi
done
